SELECT
    PRODUCTION_ORDER_ID,
    PRODUCT_ID,
    MACHINE_ID,
    QUANTITY,
    START_DATE,
    END_DATE,
    STATUS,

    PRODUCTION_DATE,
    PRODUCTION_MONTH,

    PRODUCTION_DURATION_HOURS,
    PRODUCTION_RATE_PER_HOUR,

    IS_COMPLETED,
    IS_IN_PROGRESS,
    IS_CANCELLED

FROM {{ ref('int_production_metrics') }}